swagger: "2.0"
info:
  version: "2.1"
  title: "REST API"
  contact:
    name: "Vahe Evoyan"
    url: "https://github.com/vahe-evoyan/express-service-boilerplate"
    email: "vahe@evoyan.org"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
    backgroundColor: '#0033A0'
  description: |
    # Introduction
    TBD.

    # Authentication
    TBD

    <!-- ReDoc-Inject: <security-definitions> -->

host: "api.example.com"
basePath: "/v1"
schemes:
  - "https"
x-servers:
  - url: //api.example.com/v1
    description: Live Server
  - url: //api-sandbox.example.com/v1
    description: Sandbox Server
produces:
  - "application/json"
consumes:
  - "application/json"

tags:
  - name: Users
    description: |
      A User represents a person who can login to the system, and take actions
      subject to their granted permissions.

securityDefinitions:
  JWT:
    description: |
      You can create a JSON Web Token (JWT) via our Sessions resource.
    type: basic

responses:
  AccessForbidden:
    description: "Access forbidden, invalid API-KEY was used"
    schema:
      $ref: "#/definitions/Error"
  NotFound:
    description: "Resource was not found"
    schema:
      $ref: "#/definitions/Error"
  Conflict:
    description: "Conflict"
    schema:
      $ref: "#/definitions/Error"
  InvalidDataError:
    description: "Invalid data was sent"
    schema:
      $ref: "#/definitions/InvalidError"

parameters:
  resourceId:
    name: id
    in: path
    description: The resource identifier string
    type: string
    required: true
  collectionLimit:
    name: limit
    in: query
    description: The collection items limit
    type: integer
    minimum: 0
    maximum: 1000
  collectionOffset:
    name: offset
    in: query
    description: The collection items offset
    type: integer
    minimum: 0
  mediaType:
    name: Accept
    in: header
    type: string
    enum:
      - application/json
    default: application/json
    description: The response media type

headers:
  Pagination-Total:
    description: Total items count
    type: integer
  Pagination-Limit:
    description: Items per page limit
    type: integer
  Pagination-Offset:
    description: Pagination offset
    type: integer
